version: '3'
services:
  # Rails application service
  web:
    build: .
    command: rails server -p 3001 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    networks:
      - myapp-network

  # PostgreSQL database service
  db:
    image: postgres:12 # Use the PostgreSQL version you prefer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - myapp-network
    ports:
      - "5433:5433"

networks:
  myapp-network:
    driver: bridge

volumes:
  postgres-data:
